name: Run Postman Tests (DummyJSON)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Newman
        run: npm install -g newman

      - name: Run DummyJSON Collection
        run: newman run DummyJSON-CI-CD.postman_collection.json -e DummyJSON.postman_environment.json
