name: Run Postman Collection with Newman

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Newman
        run: npm install -g newman

      - name: Run Postman Tests
        run: newman run DummyJSON-CI-CD.postman_collection.json -e DummyJSON.postman_environment.json
